# 2012 script - Leon Levy 

#### Strategy: 
1. GET all dataset metadata from 2012 existing collection
2. Extract all DOIs and dataset titles. Separate datasets with files from those without
3. Update metadata for existing datasets (Create JSON files with new metadata for each dataset (`for DOI in list_of_dois: PUT api_call --upload metadata_edit.json`))
4. Add files for datasets that still need them. 
5. Compare list of created datasets to full list and determine how many more to make. 
6. Do normal workflow for remaining images & datasets.

## 1. GET all dataset metadata

In [1]:
import requests
import pandas as pd
import json

In [2]:
base_url = "https://dataverse.harvard.edu"
api_token = "dd038035-97e1-443f-b25e-aba1f535c296"
alias = 'levy_photos_2012'

In [ ]:
#GET items in dataverse collection
headers = {'X-Dataverse-key': api_token,}

url_dataverse = '%s/api/dataverses/%s/contents' % (base_url, alias)
r = requests.get(url_dataverse, headers=headers)

with open('datasets.json', 'w') as f:
    json.dump(r.json(), f)

In [ ]:
j = open('datasets.json')
datasets = json.load(j)

In [ ]:
dois_2012 = []

for i in datasets["data"]: 
    dois_2012.append(i["identifier"])

In [ ]:
def prepend(list, str):
      
    # Using format()
    str += '{0}'
    list = [str.format(i) for i in list]
    return(list)

list = dois_2012
str = 'doi:10.7910/'
full_dois = prepend(list, str)

In [ ]:
full_dois

In [ ]:
#write dois to file
file = open('full_dois_2012.txt', 'w')
for i in full_dois:
    file.writelines(i+'\n')

file.close()

In [ ]:
#get metadata from DOIs
headers = {'X-Dataverse-key': api_token,}

for doi in full_dois:
    url_datasets = '%s/api/datasets/:persistentId/?persistentId=%s' % (base_url, doi)
    r = requests.get(url_datasets, headers=headers)
    
    with open('dataset_metadata.json', 'a') as f:
        json.dump(r.json(), f)
        f.write(",")

#### Add [ ] to the beginning and end of the json file or else it won't load
And use jq to "prettify" json into "pretty_dataset_metadata.json"

In [ ]:
e = open('pretty_dataset_metadata.json')
dataset_metadata = json.load(e)

In [ ]:
dataset_metadata[0]['data']['latestVersion']['files']

## 2. Separate datasets from those with files and those without

In [ ]:
#get all files for list of dataset dois
all_dataset_files = []
headers = {'X-Dataverse-key': api_token,}

for doi in full_dois:
    url_request = "%s/api/datasets/:persistentId/versions/:draft/files/?persistentId=%s" % (base_url, doi)
    r = requests.get(url_request, headers=headers)
    all_dataset_files.append(json.loads(r.text))

In [ ]:
#find objects with empty "data" values
for i in all_dataset_files:
    print(i['data']==[])

In [ ]:
full_dois

In [ ]:
#manually created csv file with both lists (hopefully they match up right!)

## 3. Update metadata for existing DOIs

1. Test pyDataverse - can I update metadata if DOI is in the PID column? 
2.

In [3]:
import os
from pyDataverse.utils import read_csv_as_dicts
csv_datasets_filename = 'test_dataset.csv'
#ds_data = read_csv_as_dicts(csv_datasets_filename)

In [47]:
csv_2_df = pd.read_csv('test_dataset.csv')
csv_2_df = csv_2_df.drop(columns = ['org.dataset_id', 'org.to_update'])
csv_2_df.columns = csv_2_df.columns.str.replace('dv.', '')
csv_2_df.head()

/opt/anaconda3/envs/dataverse/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until

,org.doi,termsOfUse,title,author,dsDescription,subject,keyword,language,kindOfData,dateOfDeposit,depositor,distributionDate,productionDate,productionPlace,datasetContact,geographicBoundingBox,geographicCoverage,geographicUnit,grantNumber
0,doi:10.7910/DVN/EXFTAX,Content made available under <a href='https://...,A12_23896.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."
1,doi:10.7910/DVN/NCS5JD,Content made available under <a href='https://...,A12_23895.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."
2,doi:10.7910/DVN/MSPYZ5,Content made available under <a href='https://...,A12_23894.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."
3,doi:10.7910/DVN/M9LJT8,Content made available under <a href='https://...,A12_23893.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."
4,doi:10.7910/DVN/UFQPIF,Content made available under <a href='https://...,A12_23892.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."

#### Create json string from dataframe
Trying to create multiple json files to pass as data argument for metadata update endpoint. 
(doesn't seem to work well)

In [57]:
json_data_string = csv_2_df.to_json(orient = "index")

In [58]:
json_data_obj = json.loads(json_data_string)

In [92]:
type(json_data_obj)

dict

In [93]:
for idx, item in enumerate(json_data_obj):
    out_file = open('updates/dict_%s.json' % (idx), "w")
    json.dump(item, out_file)
    out_file.close()

In [80]:
for idx, item in enumerate(dicts):
    out_file = open('updates/dict_%s.json' % (idx), "w")
    json.dump(item, out_file)
    out_file.close()

In [4]:
from pyDataverse.models import Dataset
ds_lst = []
for ds in ds_data:
    ds_obj = Dataset()
    ds_obj.set(ds)
    ds_lst.append(ds_obj)

In [5]:
base_url = "https://dataverse.harvard.edu"
api_token = "dd038035-97e1-443f-b25e-aba1f535c296"

from pyDataverse.api import NativeApi
api = NativeApi(base_url, api_token)

In [8]:
ds_data[0]['org.doi']

'doi:10.7910/DVN/EXFTAX'

In [9]:
from pyDataverse.api import NativeApi
api = NativeApi(base_url, api_token)
resp = api.get_info_version()
resp.json()

{'status': 'OK', 'data': {'version': '5.6', 'build': None}}

In [21]:
for doi, ds in zip(ds_data, ds_lst):
    print(doi['\ufefforg.dataset_id'])

1
2
3
4
5

In [30]:
for doi, ds in zip(ds_data, ds_lst):
    out_file = open('updates/%s.json' % (doi['\ufefforg.dataset_id']), "w")
    json.dump(ds.json(), out_file, separators=(',', ':'))
    out_file.close()

In [29]:
#I think the problem is the json files that come from ds.json() :((( -- either create json files directly from CSV or try removing the newlines...
for doi, ds in zip(ds_data, ds_lst):
    resp = api.edit_dataset_metadata(doi['org.doi'], 
                                     open('updates/%s.json' % (doi['\ufefforg.dataset_id'])).read(), 
                                     is_pid=True, 
                                     replace=True, 
                                     auth=True)
    print(resp.status_code)

500
500
500
500
500

In [27]:
for doi, ds in zip(ds_data, ds_lst):
    data = open('updates/%s.json' % (doi['\ufefforg.dataset_id'])).read()
    print(data)

"{\n  \"datasetVersion\": {\n    \"metadataBlocks\": {\n      \"citation\": {\n        \"fields\": [\n          {\n            \"typeName\": \"dateOfDeposit\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"2021-09-01\"\n          },\n          {\n            \"typeName\": \"depositor\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"Mika, Katherine\"\n          },\n          {\n            \"typeName\": \"distributionDate\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"2021-09-01\"\n          },\n          {\n            \"typeName\": \"kindOfData\",\n            \"multiple\": true,\n            \"typeClass\": \"primitive\",\n            \"value\": [\n              \"Photograph\"\n            ]\n          },\n          {\n            \"typeName\": \"language\",\n            \"multiple\": true,\n            \"typeClass\": \"controlledVocabulary\",\n            \"value\": [\n              \"English\"\n            ]\n          },\n          {\n            \"typeName\": \"productionDate\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"2012\"\n          },\n          {\n            \"typeName\": \"productionPlace\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"Israel\"\n          },\n          {\n            \"typeName\": \"subject\",\n            \"multiple\": true,\n            \"typeClass\": \"controlledVocabulary\",\n            \"value\": [\n              \"Arts and Humanities\"\n            ]\n          },\n          {\n            \"typeName\": \"title\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"A12_23896.JPG\"\n          },\n          {\n            \"typeName\": \"author\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"authorName\": {\n                  \"typeName\": \"authorName\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Master, Daniel M.\"\n                },\n                \"authorAffiliation\": {\n                  \"typeName\": \"authorAffiliation\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Wheaton College\"\n                }\n              },\n              {\n                \"authorName\": {\n                  \"typeName\": \"authorName\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Stager, Lawrence E.\"\n                },\n                \"authorAffiliation\": {\n                  \"typeName\": \"authorAffiliation\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Harvard University\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"datasetContact\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"datasetContactName\": {\n                  \"typeName\": \"datasetContactName\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Master, Daniel\"\n                },\n                \"datasetContactAffiliation\": {\n                  \"typeName\": \"datasetContactAffiliation\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Wheaton College\"\n                },\n                \"datasetContactEmail\": {\n                  \"typeName\": \"datasetContactEmail\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"daniel.master@wheaton.edu\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"dsDescription\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"dsDescriptionValue\": {\n                  \"typeName\": \"dsDescriptionValue\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"updated\"\n                },\n                \"dsDescriptionDate\": {\n                  \"typeName\": \"dsDescriptionDate\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"2021-05-10\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"grantNumber\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"grantNumberAgency\": {\n                  \"typeName\": \"grantNumberAgency\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"The Leon Levy Foundation\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"keyword\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"keywordValue\": {\n                  \"typeName\": \"keywordValue\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Archaeology\"\n                }\n              }\n            ]\n          }\n        ]\n      },\n      \"geospatial\": {\n        \"fields\": [\n          {\n            \"typeName\": \"geographicUnit\",\n            \"multiple\": true,\n            \"typeClass\": \"primitive\",\n            \"value\": [\n              \"City\"\n            ]\n          },\n          {\n            \"typeName\": \"geographicBoundingBox\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"westLongitude\": {\n                  \"typeName\": \"westLongitude\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"31.659769\"\n                },\n                \"eastLongitude\": {\n                  \"typeName\": \"eastLongitude\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"31.668014\"\n                },\n                \"northLongitude\": {\n                  \"typeName\": \"northLongitude\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"34.541372\"\n                },\n                \"southLongitude\": {\n                  \"typeName\": \"southLongitude\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"34.552483\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"geographicCoverage\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"city\": {\n                  \"typeName\": \"city\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Ashkelon\"\n                }\n              }\n            ]\n          }\n        ]\n      }\n    },\n    \"termsOfUse\": \"Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license. \"\n  }\n}"
"{\n  \"datasetVersion\": {\n    \"metadataBlocks\": {\n      \"citation\": {\n        \"fields\": [\n          {\n            \"typeName\": \"dateOfDeposit\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"2021-09-01\"\n          },\n          {\n            \"typeName\": \"depositor\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"Mika, Katherine\"\n          },\n          {\n            \"typeName\": \"distributionDate\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"2021-09-01\"\n          },\n          {\n            \"typeName\": \"kindOfData\",\n            \"multiple\": true,\n            \"typeClass\": \"primitive\",\n            \"value\": [\n              \"Photograph\"\n            ]\n          },\n          {\n            \"typeName\": \"language\",\n            \"multiple\": true,\n            \"typeClass\": \"controlledVocabulary\",\n            \"value\": [\n              \"English\"\n            ]\n          },\n          {\n            \"typeName\": \"productionDate\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"2012\"\n          },\n          {\n            \"typeName\": \"productionPlace\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"Israel\"\n          },\n          {\n            \"typeName\": \"subject\",\n            \"multiple\": true,\n            \"typeClass\": \"controlledVocabulary\",\n            \"value\": [\n              \"Arts and Humanities\"\n            ]\n          },\n          {\n            \"typeName\": \"title\",\n            \"multiple\": false,\n            \"typeClass\": \"primitive\",\n            \"value\": \"A12_23895.JPG\"\n          },\n          {\n            \"typeName\": \"author\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"authorName\": {\n                  \"typeName\": \"authorName\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Master, Daniel M.\"\n                },\n                \"authorAffiliation\": {\n                  \"typeName\": \"authorAffiliation\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Wheaton College\"\n                }\n              },\n              {\n                \"authorName\": {\n                  \"typeName\": \"authorName\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Stager, Lawrence E.\"\n                },\n                \"authorAffiliation\": {\n                  \"typeName\": \"authorAffiliation\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Harvard University\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"datasetContact\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"datasetContactName\": {\n                  \"typeName\": \"datasetContactName\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Master, Daniel\"\n                },\n                \"datasetContactAffiliation\": {\n                  \"typeName\": \"datasetContactAffiliation\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Wheaton College\"\n                },\n                \"datasetContactEmail\": {\n                  \"typeName\": \"datasetContactEmail\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"daniel.master@wheaton.edu\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"dsDescription\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"dsDescriptionValue\": {\n                  \"typeName\": \"dsDescriptionValue\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"updated\"\n                },\n                \"dsDescriptionDate\": {\n                  \"typeName\": \"dsDescriptionDate\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"2021-05-10\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"grantNumber\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"grantNumberAgency\": {\n                  \"typeName\": \"grantNumberAgency\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"The Leon Levy Foundation\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"keyword\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"keywordValue\": {\n                  \"typeName\": \"keywordValue\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Archaeology\"\n                }\n              }\n            ]\n          }\n        ]\n      },\n      \"geospatial\": {\n        \"fields\": [\n          {\n            \"typeName\": \"geographicUnit\",\n            \"multiple\": true,\n            \"typeClass\": \"primitive\",\n            \"value\": [\n              \"City\"\n            ]\n          },\n          {\n            \"typeName\": \"geographicBoundingBox\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"westLongitude\": {\n                  \"typeName\": \"westLongitude\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"31.659769\"\n                },\n                \"eastLongitude\": {\n                  \"typeName\": \"eastLongitude\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"31.668014\"\n                },\n                \"northLongitude\": {\n                  \"typeName\": \"northLongitude\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"34.541372\"\n                },\n                \"southLongitude\": {\n                  \"typeName\": \"southLongitude\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"34.552483\"\n                }\n              }\n            ]\n          },\n          {\n            \"typeName\": \"geographicCoverage\",\n            \"multiple\": true,\n            \"typeClass\": \"compound\",\n            \"value\": [\n              {\n                \"city\": {\n                  \"typeName\": \"city\",\n                  \"typeClass\": \"primitive\",\n                  \"multiple\": false,\n                  \"value\": \"Ashkelon\"\n                }\n              }\n            ]\n          }\n        ]\n      }\n    },\n    \"termsOfUse\": \"Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license. \"\n  }\n}"

In [19]:
headers = {'X-Dataverse-key': api_token,}

for doi, ds in zip(ds_data, ds_lst):
    #data = ds.json()
    url_update_md = '%s/api/datasets/:persistentId/editMetadata?persistentId=%s&replace=true' % (base_url, doi['org.doi'])
    r = requests.put(url_update_md, data=open('grant_info.json','r').read(), headers=headers)
    print(r.json())

{'status': 'OK', 'data': {'id': 209956, 'datasetId': 4043242, 'datasetPersistentId': 'doi:10.7910/DVN/EXFTAX', 'storageIdentifier': 's3://10.7910/DVN/EXFTAX', 'versionState': 'DRAFT', 'lastUpdateTime': '2021-09-02T16:59:17Z', 'createTime': '2020-08-28T16:21:20Z', 'license': 'NONE', 'fileAccessRequest': False, 'metadataBlocks': {'citation': {'displayName': 'Citation Metadata', 'fields': [{'typeName': 'title', 'multiple': False, 'typeClass': 'primitive', 'value': 'A12_23896.JPG'}, {'typeName': 'author', 'multiple': True, 'typeClass': 'compound', 'value': [{'authorName': {'typeName': 'authorName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Levy, Leon'}, 'authorAffiliation': {'typeName': 'authorAffiliation', 'multiple': False, 'typeClass': 'primitive', 'value': 'Harvard University'}}]}, {'typeName': 'datasetContact', 'multiple': True, 'typeClass': 'compound', 'value': [{'datasetContactName': {'typeName': 'datasetContactName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Mika, Katherine'}, 'datasetContactEmail': {'typeName': 'datasetContactEmail', 'multiple': False, 'typeClass': 'primitive', 'value': 'katherine_mika@harvard.edu'}}]}, {'typeName': 'dsDescription', 'multiple': True, 'typeClass': 'compound', 'value': [{'dsDescriptionValue': {'typeName': 'dsDescriptionValue', 'multiple': False, 'typeClass': 'primitive', 'value': '<a href="<a href = "http://pi.lib.uchicago.edu/1001/org/ochre/2d4899e8-a583-42be-a16c-a0ea1d95c94f">image metadata</a>\n\n<br/ ><br />\nOCHRE link: <a href = "http://pi.lib.uchicago.edu/1001/org/ochre/2d4899e8-a583-42be-a16c-a0ea1d95c94f">http://pi.lib.uchicago.edu/1001/org/ochre/2d4899e8-a583-42be-a16c-a0ea1d95c94f</a>'}}]}, {'typeName': 'subject', 'multiple': True, 'typeClass': 'controlledVocabulary', 'value': ['Other']}, {'typeName': 'grantNumber', 'multiple': True, 'typeClass': 'compound', 'value': [{'grantNumberAgency': {'typeName': 'grantNumberAgency', 'multiple': False, 'typeClass': 'primitive', 'value': 'National Science Foundation'}}]}]}}, 'files': []}}
{'status': 'OK', 'data': {'id': 209955, 'datasetId': 4043241, 'datasetPersistentId': 'doi:10.7910/DVN/NCS5JD', 'storageIdentifier': 's3://10.7910/DVN/NCS5JD', 'versionState': 'DRAFT', 'lastUpdateTime': '2021-09-02T16:59:21Z', 'createTime': '2020-08-28T16:21:19Z', 'license': 'NONE', 'fileAccessRequest': False, 'metadataBlocks': {'citation': {'displayName': 'Citation Metadata', 'fields': [{'typeName': 'title', 'multiple': False, 'typeClass': 'primitive', 'value': 'A12_23895.JPG'}, {'typeName': 'author', 'multiple': True, 'typeClass': 'compound', 'value': [{'authorName': {'typeName': 'authorName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Levy, Leon'}, 'authorAffiliation': {'typeName': 'authorAffiliation', 'multiple': False, 'typeClass': 'primitive', 'value': 'Harvard University'}}]}, {'typeName': 'datasetContact', 'multiple': True, 'typeClass': 'compound', 'value': [{'datasetContactName': {'typeName': 'datasetContactName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Mika, Katherine'}, 'datasetContactEmail': {'typeName': 'datasetContactEmail', 'multiple': False, 'typeClass': 'primitive', 'value': 'katherine_mika@harvard.edu'}}]}, {'typeName': 'dsDescription', 'multiple': True, 'typeClass': 'compound', 'value': [{'dsDescriptionValue': {'typeName': 'dsDescriptionValue', 'multiple': False, 'typeClass': 'primitive', 'value': 'OCHRE link: <a href = "http://pi.lib.uchicago.edu/1001/org/ochre/d98efe34-836a-4619-b251-5a6fb0aa520c">http://pi.lib.uchicago.edu/1001/org/ochre/d98efe34-836a-4619-b251-5a6fb0aa520c</a>'}}]}, {'typeName': 'subject', 'multiple': True, 'typeClass': 'controlledVocabulary', 'value': ['Other']}, {'typeName': 'grantNumber', 'multiple': True, 'typeClass': 'compound', 'value': [{'grantNumberAgency': {'typeName': 'grantNumberAgency', 'multiple': False, 'typeClass': 'primitive', 'value': 'National Science Foundation'}}]}]}}, 'files': []}}
{'status': 'OK', 'data': {'id': 209954, 'datasetId': 4043240, 'datasetPersistentId': 'doi:10.7910/DVN/MSPYZ5', 'storageIdentifier': 's3://10.7910/DVN/MSPYZ5', 'versionState': 'DRAFT', 'lastUpdateTime': '2021-09-02T16:59:24Z', 'createTime': '2020-08-28T16:21:18Z', 'license': 'NONE', 'fileAccessRequest': False, 'metadataBlocks': {'citation': {'displayName': 'Citation Metadata', 'fields': [{'typeName': 'title', 'multiple': False, 'typeClass': 'primitive', 'value': 'A12_23894.JPG'}, {'typeName': 'author', 'multiple': True, 'typeClass': 'compound', 'value': [{'authorName': {'typeName': 'authorName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Levy, Leon'}, 'authorAffiliation': {'typeName': 'authorAffiliation', 'multiple': False, 'typeClass': 'primitive', 'value': 'Harvard University'}}]}, {'typeName': 'datasetContact', 'multiple': True, 'typeClass': 'compound', 'value': [{'datasetContactName': {'typeName': 'datasetContactName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Mika, Katherine'}, 'datasetContactEmail': {'typeName': 'datasetContactEmail', 'multiple': False, 'typeClass': 'primitive', 'value': 'katherine_mika@harvard.edu'}}]}, {'typeName': 'dsDescription', 'multiple': True, 'typeClass': 'compound', 'value': [{'dsDescriptionValue': {'typeName': 'dsDescriptionValue', 'multiple': False, 'typeClass': 'primitive', 'value': 'OCHRE link: <a href = "http://pi.lib.uchicago.edu/1001/org/ochre/3ce07914-8444-407e-a663-74a581aed2b1">http://pi.lib.uchicago.edu/1001/org/ochre/3ce07914-8444-407e-a663-74a581aed2b1</a>'}}]}, {'typeName': 'subject', 'multiple': True, 'typeClass': 'controlledVocabulary', 'value': ['Other']}, {'typeName': 'grantNumber', 'multiple': True, 'typeClass': 'compound', 'value': [{'grantNumberAgency': {'typeName': 'grantNumberAgency', 'multiple': False, 'typeClass': 'primitive', 'value': 'National Science Foundation'}}]}]}}, 'files': []}}
{'status': 'OK', 'data': {'id': 209953, 'datasetId': 4043239, 'datasetPersistentId': 'doi:10.7910/DVN/M9LJT8', 'storageIdentifier': 's3://10.7910/DVN/M9LJT8', 'versionState': 'DRAFT', 'lastUpdateTime': '2021-09-02T16:59:27Z', 'createTime': '2020-08-28T16:21:17Z', 'license': 'NONE', 'fileAccessRequest': False, 'metadataBlocks': {'citation': {'displayName': 'Citation Metadata', 'fields': [{'typeName': 'title', 'multiple': False, 'typeClass': 'primitive', 'value': 'A12_23893.JPG'}, {'typeName': 'author', 'multiple': True, 'typeClass': 'compound', 'value': [{'authorName': {'typeName': 'authorName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Levy, Leon'}, 'authorAffiliation': {'typeName': 'authorAffiliation', 'multiple': False, 'typeClass': 'primitive', 'value': 'Harvard University'}}]}, {'typeName': 'datasetContact', 'multiple': True, 'typeClass': 'compound', 'value': [{'datasetContactName': {'typeName': 'datasetContactName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Mika, Katherine'}, 'datasetContactEmail': {'typeName': 'datasetContactEmail', 'multiple': False, 'typeClass': 'primitive', 'value': 'katherine_mika@harvard.edu'}}]}, {'typeName': 'dsDescription', 'multiple': True, 'typeClass': 'compound', 'value': [{'dsDescriptionValue': {'typeName': 'dsDescriptionValue', 'multiple': False, 'typeClass': 'primitive', 'value': 'OCHRE link: <a href = "http://pi.lib.uchicago.edu/1001/org/ochre/82c194ba-b6cd-4a98-b2ec-857bf025ed7c">http://pi.lib.uchicago.edu/1001/org/ochre/82c194ba-b6cd-4a98-b2ec-857bf025ed7c</a>'}}]}, {'typeName': 'subject', 'multiple': True, 'typeClass': 'controlledVocabulary', 'value': ['Other']}, {'typeName': 'grantNumber', 'multiple': True, 'typeClass': 'compound', 'value': [{'grantNumberAgency': {'typeName': 'grantNumberAgency', 'multiple': False, 'typeClass': 'primitive', 'value': 'National Science Foundation'}}]}]}}, 'files': []}}
{'status': 'OK', 'data': {'id': 209952, 'datasetId': 4043238, 'datasetPersistentId': 'doi:10.7910/DVN/UFQPIF', 'storageIdentifier': 's3://10.7910/DVN/UFQPIF', 'versionState': 'DRAFT', 'lastUpdateTime': '2021-09-02T16:59:30Z', 'createTime': '2020-08-28T16:21:16Z', 'license': 'NONE', 'fileAccessRequest': False, 'metadataBlocks': {'citation': {'displayName': 'Citation Metadata', 'fields': [{'typeName': 'title', 'multiple': False, 'typeClass': 'primitive', 'value': 'A12_23892.JPG'}, {'typeName': 'author', 'multiple': True, 'typeClass': 'compound', 'value': [{'authorName': {'typeName': 'authorName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Levy, Leon'}, 'authorAffiliation': {'typeName': 'authorAffiliation', 'multiple': False, 'typeClass': 'primitive', 'value': 'Harvard University'}}]}, {'typeName': 'datasetContact', 'multiple': True, 'typeClass': 'compound', 'value': [{'datasetContactName': {'typeName': 'datasetContactName', 'multiple': False, 'typeClass': 'primitive', 'value': 'Mika, Katherine'}, 'datasetContactEmail': {'typeName': 'datasetContactEmail', 'multiple': False, 'typeClass': 'primitive', 'value': 'katherine_mika@harvard.edu'}}]}, {'typeName': 'dsDescription', 'multiple': True, 'typeClass': 'compound', 'value': [{'dsDescriptionValue': {'typeName': 'dsDescriptionValue', 'multiple': False, 'typeClass': 'primitive', 'value': 'OCHRE link: <a href = "http://pi.lib.uchicago.edu/1001/org/ochre/926f59ec-5f7f-4169-a2e9-5a5db173af88">http://pi.lib.uchicago.edu/1001/org/ochre/926f59ec-5f7f-4169-a2e9-5a5db173af88</a>'}}]}, {'typeName': 'subject', 'multiple': True, 'typeClass': 'controlledVocabulary', 'value': ['Other']}, {'typeName': 'grantNumber', 'multiple': True, 'typeClass': 'compound', 'value': [{'grantNumberAgency': {'typeName': 'grantNumberAgency', 'multiple': False, 'typeClass': 'primitive', 'value': 'National Science Foundation'}}]}]}}, 'files': []}}

In [15]:
with open('grant_info.json') as f:
    d = json.load(f)

In [28]:
headers = {'X-Dataverse-key': api_token,}

url_update_md = '%s/api/datasets/:persistentId/editMetadata?persistentId=doi:10.7910/DVN/EXFTAX&replace=true' % (base_url)
r = requests.put(url_update_md, data=open('updates/1.json','r').read(), headers=headers)
print(r.json())

{}

In [ ]:
base_url = "https://demo.dataverse.org"
api_token = "dd038035-97e1-443f-b25e-aba1f535c296"

In [ ]:
doi = 'doi:10.70122/FK2/754QGC'
data = d
resp = api.edit_dataset_metadata(doi, data, replace=True, auth=True)
resp.status_code

In [ ]:
data['fields'][0]['value']

In [ ]:
data['fields'][0]['value'] = 'Updated Test1'

In [ ]:
data['fields'][0]['value']

In [ ]:
resp = api.edit_dataset_metadata(doi, data, replace=True, auth=True)
resp.status_code

In [ ]:
with open('test_md_update.json', 'w') as f:
        json.dump(ds_lst[0].json(), f)

#### Create dict from csv and then dump into json file

In [36]:
import csv
import json

In [6]:
filename = "test_dataset.csv"

In [13]:
with open(filename,'r') as data:
    for line in csv.DictReader(data):
        print(line['dv.dsDescription'])

[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]
[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]
[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]
[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]
[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]

In [14]:
csv_2_df = pd.read_csv('test_dataset.csv')
csv_2_df = csv_2_df.drop(columns = ['org.dataset_id', 'org.to_update'])
csv_2_df.columns = csv_2_df.columns.str.replace('dv.', '')
csv_2_df.head()

/opt/anaconda3/envs/dataverse/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until

,org.doi,termsOfUse,title,author,dsDescription,subject,keyword,language,kindOfData,dateOfDeposit,depositor,distributionDate,productionDate,productionPlace,datasetContact,geographicBoundingBox,geographicCoverage,geographicUnit,grantNumber
0,doi:10.7910/DVN/EXFTAX,Content made available under <a href='https://...,A12_23896.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."
1,doi:10.7910/DVN/NCS5JD,Content made available under <a href='https://...,A12_23895.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."
2,doi:10.7910/DVN/MSPYZ5,Content made available under <a href='https://...,A12_23894.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."
3,doi:10.7910/DVN/M9LJT8,Content made available under <a href='https://...,A12_23893.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."
4,doi:10.7910/DVN/UFQPIF,Content made available under <a href='https://...,A12_23892.JPG,"[{""authorName"": ""Master, Daniel M."", ""authorAf...","[{""dsDescriptionValue"": ""updated"", ""dsDescript...","[""Arts and Humanities""]","[{""keywordValue"": ""Archaeology""}]","[""English""]","[""Photograph""]",2021-09-01,"Mika, Katherine",2021-09-01,2012,Israel,"[{""datasetContactName"": ""Master, Daniel"", ""dat...","[{""westLongitude"": ""31.659769"", ""eastLongitude...","[{""city"": ""Ashkelon""}]","[""City""]","[{""grantNumberAgency"": ""The Leon Levy Foundati..."

In [16]:
df_2_dict = csv_2_df.to_dict(orient = "index")

In [26]:
for i in df_2_dict:
    print(i, '->', df_2_dict[i]['org.doi'])

0 -> doi:10.7910/DVN/EXFTAX
1 -> doi:10.7910/DVN/NCS5JD
2 -> doi:10.7910/DVN/MSPYZ5
3 -> doi:10.7910/DVN/M9LJT8
4 -> doi:10.7910/DVN/UFQPIF

In [35]:
for i in df_2_dict:
    print(df_2_dict[i])

{'org.doi': 'doi:10.7910/DVN/EXFTAX', 'termsOfUse': "Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license. ", 'title': 'A12_23896.JPG', 'author': '[{"authorName": "Master, Daniel M.", "authorAffiliation": "Wheaton College"}, {"authorName": "Stager, Lawrence E.", "authorAffiliation": "Harvard University"}]', 'dsDescription': '[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]', 'subject': '["Arts and Humanities"]', 'keyword': '[{"keywordValue": "Archaeology"}]', 'language': '["English"]', 'kindOfData': '["Photograph"]', 'dateOfDeposit': '2021-09-01', 'depositor': 'Mika, Katherine', 'distributionDate': '2021-09-01', 'productionDate': 2012, 'productionPlace': 'Israel', 'datasetContact': '[{"datasetContactName": "Master, Daniel", "datasetContactAffiliation": "Wheaton College", "datasetContactEmail": "daniel.master@wheaton.edu"}]', 'geographicBoundingBox': '[{"westLongitude": "31.659769", "eastLongitude": "31.668014", "northLongitude": "34.541372", "southLongitude": "34.552483"}]', 'geographicCoverage': '[{"city": "Ashkelon"}]', 'geographicUnit': '["City"]', 'grantNumber': '[{"grantNumberAgency": "The Leon Levy Foundation"}]'}
{'org.doi': 'doi:10.7910/DVN/NCS5JD', 'termsOfUse': "Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license. ", 'title': 'A12_23895.JPG', 'author': '[{"authorName": "Master, Daniel M.", "authorAffiliation": "Wheaton College"}, {"authorName": "Stager, Lawrence E.", "authorAffiliation": "Harvard University"}]', 'dsDescription': '[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]', 'subject': '["Arts and Humanities"]', 'keyword': '[{"keywordValue": "Archaeology"}]', 'language': '["English"]', 'kindOfData': '["Photograph"]', 'dateOfDeposit': '2021-09-01', 'depositor': 'Mika, Katherine', 'distributionDate': '2021-09-01', 'productionDate': 2012, 'productionPlace': 'Israel', 'datasetContact': '[{"datasetContactName": "Master, Daniel", "datasetContactAffiliation": "Wheaton College", "datasetContactEmail": "daniel.master@wheaton.edu"}]', 'geographicBoundingBox': '[{"westLongitude": "31.659769", "eastLongitude": "31.668014", "northLongitude": "34.541372", "southLongitude": "34.552483"}]', 'geographicCoverage': '[{"city": "Ashkelon"}]', 'geographicUnit': '["City"]', 'grantNumber': '[{"grantNumberAgency": "The Leon Levy Foundation"}]'}
{'org.doi': 'doi:10.7910/DVN/MSPYZ5', 'termsOfUse': "Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license. ", 'title': 'A12_23894.JPG', 'author': '[{"authorName": "Master, Daniel M.", "authorAffiliation": "Wheaton College"}, {"authorName": "Stager, Lawrence E.", "authorAffiliation": "Harvard University"}]', 'dsDescription': '[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]', 'subject': '["Arts and Humanities"]', 'keyword': '[{"keywordValue": "Archaeology"}]', 'language': '["English"]', 'kindOfData': '["Photograph"]', 'dateOfDeposit': '2021-09-01', 'depositor': 'Mika, Katherine', 'distributionDate': '2021-09-01', 'productionDate': 2012, 'productionPlace': 'Israel', 'datasetContact': '[{"datasetContactName": "Master, Daniel", "datasetContactAffiliation": "Wheaton College", "datasetContactEmail": "daniel.master@wheaton.edu"}]', 'geographicBoundingBox': '[{"westLongitude": "31.659769", "eastLongitude": "31.668014", "northLongitude": "34.541372", "southLongitude": "34.552483"}]', 'geographicCoverage': '[{"city": "Ashkelon"}]', 'geographicUnit': '["City"]', 'grantNumber': '[{"grantNumberAgency": "The Leon Levy Foundation"}]'}
{'org.doi': 'doi:10.7910/DVN/M9LJT8', 'termsOfUse': "Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license. ", 'title': 'A12_23893.JPG', 'author': '[{"authorName": "Master, Daniel M.", "authorAffiliation": "Wheaton College"}, {"authorName": "Stager, Lawrence E.", "authorAffiliation": "Harvard University"}]', 'dsDescription': '[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]', 'subject': '["Arts and Humanities"]', 'keyword': '[{"keywordValue": "Archaeology"}]', 'language': '["English"]', 'kindOfData': '["Photograph"]', 'dateOfDeposit': '2021-09-01', 'depositor': 'Mika, Katherine', 'distributionDate': '2021-09-01', 'productionDate': 2012, 'productionPlace': 'Israel', 'datasetContact': '[{"datasetContactName": "Master, Daniel", "datasetContactAffiliation": "Wheaton College", "datasetContactEmail": "daniel.master@wheaton.edu"}]', 'geographicBoundingBox': '[{"westLongitude": "31.659769", "eastLongitude": "31.668014", "northLongitude": "34.541372", "southLongitude": "34.552483"}]', 'geographicCoverage': '[{"city": "Ashkelon"}]', 'geographicUnit': '["City"]', 'grantNumber': '[{"grantNumberAgency": "The Leon Levy Foundation"}]'}
{'org.doi': 'doi:10.7910/DVN/UFQPIF', 'termsOfUse': "Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license. ", 'title': 'A12_23892.JPG', 'author': '[{"authorName": "Master, Daniel M.", "authorAffiliation": "Wheaton College"}, {"authorName": "Stager, Lawrence E.", "authorAffiliation": "Harvard University"}]', 'dsDescription': '[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]', 'subject': '["Arts and Humanities"]', 'keyword': '[{"keywordValue": "Archaeology"}]', 'language': '["English"]', 'kindOfData': '["Photograph"]', 'dateOfDeposit': '2021-09-01', 'depositor': 'Mika, Katherine', 'distributionDate': '2021-09-01', 'productionDate': 2012, 'productionPlace': 'Israel', 'datasetContact': '[{"datasetContactName": "Master, Daniel", "datasetContactAffiliation": "Wheaton College", "datasetContactEmail": "daniel.master@wheaton.edu"}]', 'geographicBoundingBox': '[{"westLongitude": "31.659769", "eastLongitude": "31.668014", "northLongitude": "34.541372", "southLongitude": "34.552483"}]', 'geographicCoverage': '[{"city": "Ashkelon"}]', 'geographicUnit': '["City"]', 'grantNumber': '[{"grantNumberAgency": "The Leon Levy Foundation"}]'}

In [37]:
df_2_dict[0]

{'org.doi': 'doi:10.7910/DVN/EXFTAX',
 'termsOfUse': "Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license. ",
 'title': 'A12_23896.JPG',
 'author': '[{"authorName": "Master, Daniel M.", "authorAffiliation": "Wheaton College"}, {"authorName": "Stager, Lawrence E.", "authorAffiliation": "Harvard University"}]',
 'dsDescription': '[{"dsDescriptionValue": "updated", "dsDescriptionDate": "2021-05-10"}]',
 'subject': '["Arts and Humanities"]',
 'keyword': '[{"keywordValue": "Archaeology"}]',
 'language': '["English"]',
 'kindOfData': '["Photograph"]',
 'dateOfDeposit': '2021-09-01',
 'depositor': 'Mika, Katherine',
 'distributionDate': '2021-09-01',
 'productionDate': 2012,
 'productionPlace': 'Israel',
 'datasetContact': '[{"datasetContactName": "Master, Daniel", "datasetContactAffiliation": "Wheaton College", "datasetContactEmail": "daniel.master@wheaton.edu"}]',
 'geographicBoundingBox': '[{"westLongitude": "31.659769", "eastLongitude": "31.668014", "northLongitude": "34.541372", "southLongitude": "34.552483"}]',
 'geographicCoverage': '[{"city": "Ashkelon"}]',
 'geographicUnit': '["City"]',
 'grantNumber': '[{"grantNumberAgency": "The Leon Levy Foundation"}]'}

In [41]:
with open('json_test.json', 'a') as f:
    json.dump(df_2_dict[0], f)

In [40]:
#test edit metadata with this json file:
headers = {'X-Dataverse-key': api_token,}

url_update_md = '%s/api/datasets/:persistentId/editMetadata?persistentId=doi:10.7910/DVN/EXFTAX&replace=true' % (base_url)
r = requests.put(url_update_md, data=open('json_test.json','r').read(), headers=headers)
print(r.json())

{}

#### Back to pyDataverse - dicts need to be transformed into json template, not just have correct key name

In [102]:
import os 
from pyDataverse.utils import read_csv_as_dicts
file = "test_dataset.csv"
ds_dicts = read_csv_as_dicts(file)

In [103]:
for i in ds_dicts:
    del i["\ufefforg.dataset_id"]
    del i['org.doi']
    del i['org.to_update']

In [104]:
ds_dicts[0]

{'termsOfUse': "Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license. ",
 'title': 'A12_23896.JPG',
 'author': [{'authorName': 'Master, Daniel M.',
   'authorAffiliation': 'Wheaton College'},
  {'authorName': 'Stager, Lawrence E.',
   'authorAffiliation': 'Harvard University'}],
 'dsDescription': [{'dsDescriptionValue': 'updated',
   'dsDescriptionDate': '2021-05-10'}],
 'subject': ['Arts and Humanities'],
 'keyword': [{'keywordValue': 'Archaeology'}],
 'language': ['English'],
 'kindOfData': ['Photograph'],
 'dateOfDeposit': '2021-09-01',
 'depositor': 'Mika, Katherine',
 'distributionDate': '2021-09-01',
 'productionDate': '2012',
 'productionPlace': 'Israel',
 'datasetContact': [{'datasetContactName': 'Master, Daniel',
   'datasetContactAffiliation': 'Wheaton College',
   'datasetContactEmail': 'daniel.master@wheaton.edu'}],
 'geographicBoundingBox': [{'westLongitude': '31.659769',
   'eastLongitude': '31.668014',
   'northLongitude': '34.541372',
   'southLongitude': '34.552483'}],
 'geographicCoverage': [{'city': 'Ashkelon'}],
 'geographicUnit': ['City'],
 'grantNumber': [{'grantNumberAgency': 'The Leon Levy Foundation'}]}

In [49]:
from pyDataverse.utils import write_json

In [52]:
write_json("json_test.json", ds_dicts[0])

In [61]:
#test edit metadata with this json file:
headers = {'X-Dataverse-key': api_token,}

url_update_md = '%s/api/datasets/:persistentId/editMetadata?persistentId=doi:10.7910/DVN/EXFTAX&replace=true' % (base_url)
r = requests.put(url_update_md, data=open('json_test.json','r').read(), headers=headers)
print(r.json())

{}

In [74]:
from pyDataverse.models import DVObject
from pyDataverse.models import Dataset

In [106]:
ds_obj = DVObject()
ds_obj.set(ds_dicts[0])

AttributeError: 'DVObject' object has no attribute '_internal_attributes'

In [79]:
for key, val in ds_dicts[0].items():
    print(key, val)

﻿org.dataset_id 1
org.doi doi:10.7910/DVN/EXFTAX
org.to_update True
termsOfUse Content made available under <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/'>CC BY-NC-ND 4.0</a> license.
title A12_23896.JPG
author [{'authorName': 'Master, Daniel M.', 'authorAffiliation': 'Wheaton College'}, {'authorName': 'Stager, Lawrence E.', 'authorAffiliation': 'Harvard University'}]
dsDescription [{'dsDescriptionValue': 'updated', 'dsDescriptionDate': '2021-05-10'}]
subject ['Arts and Humanities']
keyword [{'keywordValue': 'Archaeology'}]
language ['English']
kindOfData ['Photograph']
dateOfDeposit 2021-09-01
depositor Mika, Katherine
distributionDate 2021-09-01
productionDate 2012
productionPlace Israel
datasetContact [{'datasetContactName': 'Master, Daniel', 'datasetContactAffiliation': 'Wheaton College', 'datasetContactEmail': 'daniel.master@wheaton.edu'}]
geographicBoundingBox [{'westLongitude': '31.659769', 'eastLongitude': '31.668014', 'northLongitude': '34.541372', 'southLongitude': '34.552483'}]
geographicCoverage [{'city': 'Ashkelon'}]
geographicUnit ['City']
grantNumber [{'grantNumberAgency': 'The Leon Levy Foundation'}]

In [76]:
dataset = Dataset()
dataset.set(ds_dicts[0])
dataset.json()

'{\n  "datasetVersion": {\n    "metadataBlocks": {\n      "citation": {\n        "fields": [\n          {\n            "typeName": "dateOfDeposit",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "2021-09-01"\n          },\n          {\n            "typeName": "depositor",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "Mika, Katherine"\n          },\n          {\n            "typeName": "distributionDate",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "2021-09-01"\n          },\n          {\n            "typeName": "kindOfData",\n            "multiple": true,\n            "typeClass": "primitive",\n            "value": [\n              "Photograph"\n            ]\n          },\n          {\n            "typeName": "language",\n            "multiple": true,\n            "typeClass": "controlledVocabulary",\n            "value": [\n              "English"\n            ]\n          },\n          {\n            "typeName": "productionDate",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "2012"\n          },\n          {\n            "typeName": "productionPlace",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "Israel"\n          },\n          {\n            "typeName": "subject",\n            "multiple": true,\n            "typeClass": "controlledVocabulary",\n            "value": [\n              "Arts and Humanities"\n            ]\n          },\n          {\n            "typeName": "title",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "A12_23896.JPG"\n          },\n          {\n            "typeName": "author",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "authorName": {\n                  "typeName": "authorName",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Master, Daniel M."\n                },\n                "authorAffiliation": {\n                  "typeName": "authorAffiliation",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Wheaton College"\n                }\n              },\n              {\n                "authorName": {\n                  "typeName": "authorName",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Stager, Lawrence E."\n                },\n                "authorAffiliation": {\n                  "typeName": "authorAffiliation",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Harvard University"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "datasetContact",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "datasetContactName": {\n                  "typeName": "datasetContactName",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Master, Daniel"\n                },\n                "datasetContactAffiliation": {\n                  "typeName": "datasetContactAffiliation",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Wheaton College"\n                },\n                "datasetContactEmail": {\n                  "typeName": "datasetContactEmail",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "daniel.master@wheaton.edu"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "dsDescription",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "dsDescriptionValue": {\n                  "typeName": "dsDescriptionValue",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "updated"\n                },\n                "dsDescriptionDate": {\n                  "typeName": "dsDescriptionDate",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "2021-05-10"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "grantNumber",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "grantNumberAgency": {\n                  "typeName": "grantNumberAgency",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "The Leon Levy Foundation"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "keyword",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "keywordValue": {\n                  "typeName": "keywordValue",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Archaeology"\n                }\n              }\n            ]\n          }\n        ]\n      },\n      "geospatial": {\n        "fields": [\n          {\n            "typeName": "geographicUnit",\n            "multiple": true,\n            "typeClass": "primitive",\n            "value": [\n              "City"\n            ]\n          },\n          {\n            "typeName": "geographicBoundingBox",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "westLongitude": {\n                  "typeName": "westLongitude",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "31.659769"\n                },\n                "eastLongitude": {\n                  "typeName": "eastLongitude",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "31.668014"\n                },\n                "northLongitude": {\n                  "typeName": "northLongitude",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "34.541372"\n                },\n                "southLongitude": {\n                  "typeName": "southLongitude",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "34.552483"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "geographicCoverage",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "city": {\n                  "typeName": "city",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Ashkelon"\n                }\n              }\n            ]\n          }\n        ]\n      }\n    },\n    "termsOfUse": "Content made available under <a href=\'https://creativecommons.org/licenses/by-nc-nd/4.0/\'>CC BY-NC-ND 4.0</a> license. "\n  }\n}'

In [58]:
ds_obj.json()

'{\n  "datasetVersion": {\n    "metadataBlocks": {\n      "citation": {\n        "fields": [\n          {\n            "typeName": "dateOfDeposit",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "2021-09-01"\n          },\n          {\n            "typeName": "depositor",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "Mika, Katherine"\n          },\n          {\n            "typeName": "distributionDate",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "2021-09-01"\n          },\n          {\n            "typeName": "kindOfData",\n            "multiple": true,\n            "typeClass": "primitive",\n            "value": [\n              "Photograph"\n            ]\n          },\n          {\n            "typeName": "language",\n            "multiple": true,\n            "typeClass": "controlledVocabulary",\n            "value": [\n              "English"\n            ]\n          },\n          {\n            "typeName": "productionDate",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "2012"\n          },\n          {\n            "typeName": "productionPlace",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "Israel"\n          },\n          {\n            "typeName": "subject",\n            "multiple": true,\n            "typeClass": "controlledVocabulary",\n            "value": [\n              "Arts and Humanities"\n            ]\n          },\n          {\n            "typeName": "title",\n            "multiple": false,\n            "typeClass": "primitive",\n            "value": "A12_23896.JPG"\n          },\n          {\n            "typeName": "author",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "authorName": {\n                  "typeName": "authorName",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Master, Daniel M."\n                },\n                "authorAffiliation": {\n                  "typeName": "authorAffiliation",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Wheaton College"\n                }\n              },\n              {\n                "authorName": {\n                  "typeName": "authorName",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Stager, Lawrence E."\n                },\n                "authorAffiliation": {\n                  "typeName": "authorAffiliation",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Harvard University"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "datasetContact",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "datasetContactName": {\n                  "typeName": "datasetContactName",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Master, Daniel"\n                },\n                "datasetContactAffiliation": {\n                  "typeName": "datasetContactAffiliation",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Wheaton College"\n                },\n                "datasetContactEmail": {\n                  "typeName": "datasetContactEmail",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "daniel.master@wheaton.edu"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "dsDescription",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "dsDescriptionValue": {\n                  "typeName": "dsDescriptionValue",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "updated"\n                },\n                "dsDescriptionDate": {\n                  "typeName": "dsDescriptionDate",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "2021-05-10"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "grantNumber",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "grantNumberAgency": {\n                  "typeName": "grantNumberAgency",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "The Leon Levy Foundation"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "keyword",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "keywordValue": {\n                  "typeName": "keywordValue",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Archaeology"\n                }\n              }\n            ]\n          }\n        ]\n      },\n      "geospatial": {\n        "fields": [\n          {\n            "typeName": "geographicUnit",\n            "multiple": true,\n            "typeClass": "primitive",\n            "value": [\n              "City"\n            ]\n          },\n          {\n            "typeName": "geographicBoundingBox",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "westLongitude": {\n                  "typeName": "westLongitude",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "31.659769"\n                },\n                "eastLongitude": {\n                  "typeName": "eastLongitude",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "31.668014"\n                },\n                "northLongitude": {\n                  "typeName": "northLongitude",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "34.541372"\n                },\n                "southLongitude": {\n                  "typeName": "southLongitude",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "34.552483"\n                }\n              }\n            ]\n          },\n          {\n            "typeName": "geographicCoverage",\n            "multiple": true,\n            "typeClass": "compound",\n            "value": [\n              {\n                "city": {\n                  "typeName": "city",\n                  "typeClass": "primitive",\n                  "multiple": false,\n                  "value": "Ashkelon"\n                }\n              }\n            ]\n          }\n        ]\n      }\n    },\n    "termsOfUse": "Content made available under <a href=\'https://creativecommons.org/licenses/by-nc-nd/4.0/\'>CC BY-NC-ND 4.0</a> license. "\n  }\n}'

In [60]:
with open('json_test.json', 'a') as f:
    json.dump(ds_obj.json(), f)

In [62]:
#try to create a dataset just to check...
from pyDataverse.api import NativeApi
api = NativeApi(base_url, api_token)

In [63]:
dv_alias = "levy_photos_2012"
resp = api.create_dataset(dv_alias, ds_obj.json())
#dataset_id_2_pid[ds.get()["org.dataset_id"]] = resp.json()["data"]["persistentId"]

Dataset with pid 'doi:10.7910/DVN/I7Q1QW' created.

In [65]:
doi = "doi:10.7910/DVN/EXFTAX"
resp = api.edit_dataset_metadata(doi, ds_obj.json(), is_pid = True, replace = True, auth = True)

### No way to do this in pyDataverse - either hitting a bug or I just don't understand python/

## Double check that all posssible files have been uploaded

In [1]:
import pandas as pd
import json
import requests

In [3]:
api_token = "899c1144-ae22-4e5e-b89d-c73e2993694f"
base_url = "https://dataverse.harvard.edu"
ID = "levy_photos_2012"

headers = {'X-Dataverse-key': api_token,}

In [2]:
with open("2012/2012_dois.txt", "r") as f:
    doi_file = f.readlines()
    f.close()
    
dois = []
for d in doi_file:
    dois.append(d.rstrip())

dois

['doi:10.7910/DVN/RQUTGG',
 'doi:10.7910/DVN/U4B96B',
 'doi:10.7910/DVN/SUJKSQ',
 'doi:10.7910/DVN/0KRANR',
 'doi:10.7910/DVN/SVT1ND',
 'doi:10.7910/DVN/VYTVBS',
 'doi:10.7910/DVN/TYUPIJ',
 'doi:10.7910/DVN/GESSWE',
 'doi:10.7910/DVN/LTWE5K',
 'doi:10.7910/DVN/HHOLY6',
 'doi:10.7910/DVN/VBUIAA',
 'doi:10.7910/DVN/B5PWMZ',
 'doi:10.7910/DVN/8OJJXV',
 'doi:10.7910/DVN/KZOL68',
 'doi:10.7910/DVN/GEPETL',
 'doi:10.7910/DVN/EOKE9C',
 'doi:10.7910/DVN/EK842P',
 'doi:10.7910/DVN/CMZRCT',
 'doi:10.7910/DVN/2IFS2G',
 'doi:10.7910/DVN/4J63MR',
 'doi:10.7910/DVN/JTC5Y3',
 'doi:10.7910/DVN/WWEE4L',
 'doi:10.7910/DVN/AOG2OF',
 'doi:10.7910/DVN/F05RZM',
 'doi:10.7910/DVN/LAFD5X',
 'doi:10.7910/DVN/B0QQNQ',
 'doi:10.7910/DVN/BM11LP',
 'doi:10.7910/DVN/F3GGQN',
 'doi:10.7910/DVN/BXAHXK',
 'doi:10.7910/DVN/9Q8DVD',
 'doi:10.7910/DVN/7G7UXQ',
 'doi:10.7910/DVN/NZMM3O',
 'doi:10.7910/DVN/M2DYOO',
 'doi:10.7910/DVN/DQDVL0',
 'doi:10.7910/DVN/QKGCEY',
 'doi:10.7910/DVN/ORUM9U',
 'doi:10.7910/DVN/9HUCYK',
 'doi:10.7910/DVN/XB2W3S',
 'doi:10.7910/DVN/NFTNBB',
 'doi:10.7910/DVN/MNP0XO',
 'doi:10.7910/DVN/JLKC2K',
 'doi:10.7910/DVN/NMVBDO',
 'doi:10.7910/DVN/DGKLRP',
 'doi:10.7910/DVN/4XPJP3',
 'doi:10.7910/DVN/VXQG4C',
 'doi:10.7910/DVN/AEQIMI',
 'doi:10.7910/DVN/TBT6WZ',
 'doi:10.7910/DVN/8WDWTH',
 'doi:10.7910/DVN/KOO6UI',
 'doi:10.7910/DVN/6U4QZG',
 'doi:10.7910/DVN/DRW4AU',
 'doi:10.7910/DVN/FKQ1WL',
 'doi:10.7910/DVN/CJMXVK',
 'doi:10.7910/DVN/QYFVM0',
 'doi:10.7910/DVN/IIHBIC',
 'doi:10.7910/DVN/BQWJXC',
 'doi:10.7910/DVN/5DCBGW',
 'doi:10.7910/DVN/G1TWJJ',
 'doi:10.7910/DVN/HVMRAU',
 'doi:10.7910/DVN/WR6MZJ',
 'doi:10.7910/DVN/QLN19P',
 'doi:10.7910/DVN/H9ELL7',
 'doi:10.7910/DVN/7HNBY7',
 'doi:10.7910/DVN/A4PSIZ',
 'doi:10.7910/DVN/27DTSR',
 'doi:10.7910/DVN/VJIZND',
 'doi:10.7910/DVN/DQACZJ',
 'doi:10.7910/DVN/AXRHQS',
 'doi:10.7910/DVN/24OOQM',
 'doi:10.7910/DVN/WEAEQH',
 'doi:10.7910/DVN/6OA7MR',
 'doi:10.7910/DVN/R1ZCG9',
 'doi:10.7910/DVN/GH4WJU',
 'doi:10.7910/DVN/R00NTI',
 'doi:10.7910/DVN/WTHCUU',
 'doi:10.7910/DVN/KUXNU4',
 'doi:10.7910/DVN/VZ4IUM',
 'doi:10.7910/DVN/CHCM5X',
 'doi:10.7910/DVN/VNRSCW',
 'doi:10.7910/DVN/LKZN94',
 'doi:10.7910/DVN/79T6FH',
 'doi:10.7910/DVN/HL92BL',
 'doi:10.7910/DVN/AIGFOD',
 'doi:10.7910/DVN/XFJOVW',
 'doi:10.7910/DVN/TSMXET',
 'doi:10.7910/DVN/GCQJIC',
 'doi:10.7910/DVN/SRV9JJ',
 'doi:10.7910/DVN/8CLBO4',
 'doi:10.7910/DVN/ZWNPIP',
 'doi:10.7910/DVN/R8OU2E',
 'doi:10.7910/DVN/GSE1BU',
 'doi:10.7910/DVN/HZVBGK',
 'doi:10.7910/DVN/QWF9HE',
 'doi:10.7910/DVN/UWEH03',
 'doi:10.7910/DVN/4OOGPF',
 'doi:10.7910/DVN/6H3TCV',
 'doi:10.7910/DVN/ADCZJZ',
 'doi:10.7910/DVN/AIRCGB',
 'doi:10.7910/DVN/6OSHYM',
 'doi:10.7910/DVN/SQXP1L',
 'doi:10.7910/DVN/Z48OU1',
 'doi:10.7910/DVN/TLJYFT',
 'doi:10.7910/DVN/AFE2GE',
 'doi:10.7910/DVN/JBJYWJ',
 'doi:10.7910/DVN/QJ9BRQ',
 'doi:10.7910/DVN/Z8GROT',
 'doi:10.7910/DVN/EQBWES',
 'doi:10.7910/DVN/S30BJX',
 'doi:10.7910/DVN/OHQZRQ',
 'doi:10.7910/DVN/24MJ22',
 'doi:10.7910/DVN/SD3OAU',
 'doi:10.7910/DVN/MZNKBY',
 'doi:10.7910/DVN/MERRRP',
 'doi:10.7910/DVN/ZXCLJN',
 'doi:10.7910/DVN/9B6FFE',
 'doi:10.7910/DVN/LRIBGW',
 'doi:10.7910/DVN/IFYU8W',
 'doi:10.7910/DVN/ER31R9',
 'doi:10.7910/DVN/JCUZNK',
 'doi:10.7910/DVN/PYS5TD',
 'doi:10.7910/DVN/35B4JA',
 'doi:10.7910/DVN/EHGNTO',
 'doi:10.7910/DVN/KZXVBZ',
 'doi:10.7910/DVN/B90BMO',
 'doi:10.7910/DVN/O7NWRK',
 'doi:10.7910/DVN/9BGVDE',
 'doi:10.7910/DVN/4GM7NU',
 'doi:10.7910/DVN/MTDP5V',
 'doi:10.7910/DVN/TSM4CS',
 'doi:10.7910/DVN/KF7A69',
 'doi:10.7910/DVN/G70IW2',
 'doi:10.7910/DVN/IGRQZS',
 'doi:10.7910/DVN/MZGEEP',
 'doi:10.7910/DVN/GH8KSW',
 'doi:10.7910/DVN/IUNE6I',
 'doi:10.7910/DVN/RWHGTB',
 'doi:10.7910/DVN/DD5PUW',
 'doi:10.7910/DVN/PNXXQE',
 'doi:10.7910/DVN/QOQJ8Y',
 'doi:10.7910/DVN/HXIDZW',
 'doi:10.7910/DVN/JXLDTJ',
 'doi:10.7910/DVN/MQA1JX',
 'doi:10.7910/DVN/G7C0QK',
 'doi:10.7910/DVN/BEX4AT',
 'doi:10.7910/DVN/IHKRMA',
 'doi:10.7910/DVN/LLEBIX',
 'doi:10.7910/DVN/IOHNWA',
 'doi:10.7910/DVN/BZX609',
 'doi:10.7910/DVN/MNTLNX',
 'doi:10.7910/DVN/G6VA1K',
 'doi:10.7910/DVN/EYN3G0',
 'doi:10.7910/DVN/NXZLDQ',
 'doi:10.7910/DVN/Y1BGDH',
 'doi:10.7910/DVN/9VMKXH',
 'doi:10.7910/DVN/F5UUGK',
 'doi:10.7910/DVN/TJ1CXW',
 'doi:10.7910/DVN/7M50BH',
 'doi:10.7910/DVN/LVAHUH',
 'doi:10.7910/DVN/MEBMN4',
 'doi:10.7910/DVN/GT6V1D',
 'doi:10.7910/DVN/CXU88C',
 'doi:10.7910/DVN/4EMX43',
 'doi:10.7910/DVN/DBOKDA',
 'doi:10.7910/DVN/HTL0BW',
 'doi:10.7910/DVN/SPGEFP',
 'doi:10.7910/DVN/BNVZUR',
 'doi:10.7910/DVN/YWNPFF',
 'doi:10.7910/DVN/DFZERR',
 'doi:10.7910/DVN/AWOM1D',
 'doi:10.7910/DVN/BEIOUZ',
 'doi:10.7910/DVN/LAYLGH',
 'doi:10.7910/DVN/KYTJZK',
 'doi:10.7910/DVN/MI1CJA',
 'doi:10.7910/DVN/CADNEE',
 'doi:10.7910/DVN/V7OIWL',
 'doi:10.7910/DVN/6ZE4P2',
 'doi:10.7910/DVN/RTNMLP',
 'doi:10.7910/DVN/LGFGMC',
 'doi:10.7910/DVN/SD70OC',
 'doi:10.7910/DVN/BC38RO',
 'doi:10.7910/DVN/H2BP2Q',
 'doi:10.7910/DVN/MEZ56C',
 'doi:10.7910/DVN/5F1KJC',
 'doi:10.7910/DVN/PGAT45',
 'doi:10.7910/DVN/ZSY9FQ',
 'doi:10.7910/DVN/DYHUSN',
 'doi:10.7910/DVN/U8FG1B',
 'doi:10.7910/DVN/RQQDV8',
 'doi:10.7910/DVN/C0DDUZ',
 'doi:10.7910/DVN/PG8EY6',
 'doi:10.7910/DVN/VCY7NK',
 'doi:10.7910/DVN/PSL2DP',
 'doi:10.7910/DVN/X8KGUP',
 'doi:10.7910/DVN/1EQ4ZR',
 'doi:10.7910/DVN/J68SV1',
 'doi:10.7910/DVN/AAANQ4',
 'doi:10.7910/DVN/8PFRNP',
 'doi:10.7910/DVN/LQIBYZ',
 'doi:10.7910/DVN/U3WHUL',
 'doi:10.7910/DVN/ZUVLP8',
 'doi:10.7910/DVN/QX4CCO',
 'doi:10.7910/DVN/OGMY4K',
 'doi:10.7910/DVN/LG1DIY',
 'doi:10.7910/DVN/33BJUB',
 'doi:10.7910/DVN/NCAO8D',
 'doi:10.7910/DVN/N8KXBA',
 'doi:10.7910/DVN/WYRMTB',
 'doi:10.7910/DVN/Q9JNVZ',
 'doi:10.7910/DVN/JOYXHI',
 'doi:10.7910/DVN/6ZQIDI',
 'doi:10.7910/DVN/NP4EJ6',
 'doi:10.7910/DVN/SIEJFH',
 'doi:10.7910/DVN/5ZGXP3',
 'doi:10.7910/DVN/CTCTRJ',
 'doi:10.7910/DVN/ARWSBL',
 'doi:10.7910/DVN/KNJEVU',
 'doi:10.7910/DVN/IZHMYO',
 'doi:10.7910/DVN/WDVMPB',
 'doi:10.7910/DVN/WRIWWD',
 'doi:10.7910/DVN/GUSORS',
 'doi:10.7910/DVN/NF09TY',
 'doi:10.7910/DVN/0WXLCI',
 'doi:10.7910/DVN/VMGXTY',
 'doi:10.7910/DVN/8FXAZK',
 'doi:10.7910/DVN/HFCZ2P',
 'doi:10.7910/DVN/JSJDQJ',
 'doi:10.7910/DVN/OTPVJ0',
 'doi:10.7910/DVN/BICMOS',
 'doi:10.7910/DVN/XUQHOP',
 'doi:10.7910/DVN/BX4RQI',
 'doi:10.7910/DVN/I0FFOW',
 'doi:10.7910/DVN/XCEP3L',
 'doi:10.7910/DVN/AWWNIC',
 'doi:10.7910/DVN/8NN9YM',
 'doi:10.7910/DVN/6OFTX7',
 'doi:10.7910/DVN/VQ4N39',
 'doi:10.7910/DVN/HSX2XK',
 'doi:10.7910/DVN/VPW6MC',
 'doi:10.7910/DVN/UD9IEU',
 'doi:10.7910/DVN/LNTU5E',
 'doi:10.7910/DVN/EZJE9B',
 'doi:10.7910/DVN/IQJAIV',
 'doi:10.7910/DVN/DYQVBA',
 'doi:10.7910/DVN/CUWDYZ',
 'doi:10.7910/DVN/1OCQYR',
 'doi:10.7910/DVN/K2OFBR',
 'doi:10.7910/DVN/BGWR0S',
 'doi:10.7910/DVN/IR5IG0',
 'doi:10.7910/DVN/5QL5NV',
 'doi:10.7910/DVN/QLDYXT',
 'doi:10.7910/DVN/5RGBAM',
 'doi:10.7910/DVN/IS7OLT',
 'doi:10.7910/DVN/XZWTPJ',
 'doi:10.7910/DVN/B7IE3V',
 'doi:10.7910/DVN/RZTC9D',
 'doi:10.7910/DVN/K2RONU',
 'doi:10.7910/DVN/SZYNWL',
 'doi:10.7910/DVN/GAAVEO',
 'doi:10.7910/DVN/FTWLQ5',
 'doi:10.7910/DVN/XSPGIO',
 'doi:10.7910/DVN/THBA5M',
 'doi:10.7910/DVN/JZXFUR',
 'doi:10.7910/DVN/MHZ9IN',
 'doi:10.7910/DVN/4051TV',
 'doi:10.7910/DVN/T4TGSX',
 'doi:10.7910/DVN/H3NLLU',
 'doi:10.7910/DVN/MM86KL',
 'doi:10.7910/DVN/XXZMDA',
 'doi:10.7910/DVN/GDSORD',
 'doi:10.7910/DVN/DODY45',
 'doi:10.7910/DVN/JSLPD6',
 'doi:10.7910/DVN/LDYCXX',
 'doi:10.7910/DVN/GJY47R',
 'doi:10.7910/DVN/YKNWZR',
 'doi:10.7910/DVN/BJ63NV',
 'doi:10.7910/DVN/WGXZGF',
 'doi:10.7910/DVN/ZJOQBI',
 'doi:10.7910/DVN/BJ52GA',
 'doi:10.7910/DVN/3SVW8E',
 'doi:10.7910/DVN/QSQWRW',
 'doi:10.7910/DVN/ATU6NO',
 'doi:10.7910/DVN/UERRJP',
 'doi:10.7910/DVN/HGZNPG',
 'doi:10.7910/DVN/CLGN6Y',
 'doi:10.7910/DVN/HA6WQH',
 'doi:10.7910/DVN/QTDUDX',
 'doi:10.7910/DVN/W5MCUJ',
 'doi:10.7910/DVN/EUKH1V',
 'doi:10.7910/DVN/VDNQD6',
 'doi:10.7910/DVN/0MBUXH',
 'doi:10.7910/DVN/8Z6GSS',
 'doi:10.7910/DVN/TVEUNW',
 'doi:10.7910/DVN/JCUOSI',
 'doi:10.7910/DVN/QIJVY2',
 'doi:10.7910/DVN/0JKXSX',
 'doi:10.7910/DVN/6K4C01',
 'doi:10.7910/DVN/L8OIA1',
 'doi:10.7910/DVN/KKBD1Y',
 'doi:10.7910/DVN/UXLPQP',
 'doi:10.7910/DVN/YPESCA',
 'doi:10.7910/DVN/HF7QTP',
 'doi:10.7910/DVN/SP6TDY',
 'doi:10.7910/DVN/O9GWCS',
 'doi:10.7910/DVN/HI6V5O',
 'doi:10.7910/DVN/RVQEGO',
 'doi:10.7910/DVN/LOKM83',
 'doi:10.7910/DVN/TELZSN',
 'doi:10.7910/DVN/6JW8WB',
 'doi:10.7910/DVN/5UFPRR',
 'doi:10.7910/DVN/B6KYCJ',
 'doi:10.7910/DVN/7Y7YXW',
 'doi:10.7910/DVN/YWALIM',
 'doi:10.7910/DVN/DXU1Z5',
 'doi:10.7910/DVN/PBP5A8',
 'doi:10.7910/DVN/PETB2H',
 'doi:10.7910/DVN/GRJWDV',
 'doi:10.7910/DVN/B3LVWN',
 'doi:10.7910/DVN/PASGNX',
 'doi:10.7910/DVN/B69L8S',
 'doi:10.7910/DVN/6PMHKF',
 'doi:10.7910/DVN/JX89RL',
 'doi:10.7910/DVN/TIHJJT',
 'doi:10.7910/DVN/ULU2XV',
 'doi:10.7910/DVN/2QAIKE',
 'doi:10.7910/DVN/LXYEPP',
 'doi:10.7910/DVN/OMZLX5',
 'doi:10.7910/DVN/09TVGV',
 'doi:10.7910/DVN/KMLBTE',
 'doi:10.7910/DVN/QFSZMW',
 'doi:10.7910/DVN/KD69WJ',
 'doi:10.7910/DVN/NMMGHS',
 'doi:10.7910/DVN/9HEDBV',
 'doi:10.7910/DVN/LRSSYN',
 'doi:10.7910/DVN/M9FLL5',
 'doi:10.7910/DVN/PNV5VN',
 'doi:10.7910/DVN/UAAY41',
 'doi:10.7910/DVN/VI0MTP',
 'doi:10.7910/DVN/1LHLVO',
 'doi:10.7910/DVN/G6A205',
 'doi:10.7910/DVN/ZTQNPE',
 'doi:10.7910/DVN/D2YHXK',
 'doi:10.7910/DVN/Q4Y2OU',
 'doi:10.7910/DVN/FNN4EF',
 'doi:10.7910/DVN/8BJMPZ',
 'doi:10.7910/DVN/7EEGD2',
 'doi:10.7910/DVN/PDZB3X',
 'doi:10.7910/DVN/5LG5YG',
 'doi:10.7910/DVN/VNECSM',
 'doi:10.7910/DVN/E0JNTH',
 'doi:10.7910/DVN/3EZLQU',
 'doi:10.7910/DVN/5BJYGD',
 'doi:10.7910/DVN/WMLH7V',
 'doi:10.7910/DVN/PJHKQV',
 'doi:10.7910/DVN/6TRH4P',
 'doi:10.7910/DVN/GPQZLA',
 'doi:10.7910/DVN/YR1R4Q',
 'doi:10.7910/DVN/CJ89AJ',
 'doi:10.7910/DVN/68CTCQ',
 'doi:10.7910/DVN/AHGQIJ',
 'doi:10.7910/DVN/CBUC33',
 'doi:10.7910/DVN/QE4GCJ',
 'doi:10.7910/DVN/DAEWS3',
 'doi:10.7910/DVN/QVO2MN',
 'doi:10.7910/DVN/C8LYNM',
 'doi:10.7910/DVN/WGXF4Z',
 'doi:10.7910/DVN/CQKVHL',
 'doi:10.7910/DVN/TXJLYP',
 'doi:10.7910/DVN/2LTZW8',
 'doi:10.7910/DVN/UCXS8L',
 'doi:10.7910/DVN/HKKHXV',
 'doi:10.7910/DVN/RC7W5Z',
 'doi:10.7910/DVN/GZ1ESL',
 'doi:10.7910/DVN/SBE19S',
 'doi:10.7910/DVN/LJGPGR',
 'doi:10.7910/DVN/1ZXHUH',
 'doi:10.7910/DVN/40L0TG',
 'doi:10.7910/DVN/Z8ATTV',
 'doi:10.7910/DVN/HRW4N3',
 'doi:10.7910/DVN/TAOIYO',
 'doi:10.7910/DVN/1TIPTB',
 'doi:10.7910/DVN/LMGHTT',
 'doi:10.7910/DVN/MMIMFY',
 'doi:10.7910/DVN/KWW25X',
 'doi:10.7910/DVN/XCKR6B',
 'doi:10.7910/DVN/CYZ84G',
 'doi:10.7910/DVN/HELSOR',
 'doi:10.7910/DVN/FKZGTK',
 'doi:10.7910/DVN/OO8WLP',
 'doi:10.7910/DVN/AJROFP',
 'doi:10.7910/DVN/NVTBEE',
 'doi:10.7910/DVN/CWIBKH',
 'doi:10.7910/DVN/J5AMRJ',
 'doi:10.7910/DVN/ZCGT07',
 'doi:10.7910/DVN/JH9BFF',
 'doi:10.7910/DVN/K06S90',
 'doi:10.7910/DVN/KOIAYP',
 'doi:10.7910/DVN/MVWM1X',
 'doi:10.7910/DVN/UIJDTF',
 'doi:10.7910/DVN/WFIQRS',
 'doi:10.7910/DVN/IJ89LJ',
 'doi:10.7910/DVN/LAY3VQ',
 'doi:10.7910/DVN/OQVEXT',
 'doi:10.7910/DVN/P2AGJM',
 'doi:10.7910/DVN/MQPZYV',
 'doi:10.7910/DVN/KACV75',
 'doi:10.7910/DVN/SQWFQK',
 'doi:10.7910/DVN/LFBNIK',
 'doi:10.7910/DVN/630GDP',
 'doi:10.7910/DVN/SFBWLL',
 'doi:10.7910/DVN/NYIAEK',
 'doi:10.7910/DVN/OCHTVL',
 'doi:10.7910/DVN/ARRIPI',
 'doi:10.7910/DVN/1JLJ9K',
 'doi:10.7910/DVN/C4J8QJ',
 'doi:10.7910/DVN/RA888V',
 'doi:10.7910/DVN/FF4OOW',
 'doi:10.7910/DVN/OSK2KK',
 'doi:10.7910/DVN/1QBPE0',
 'doi:10.7910/DVN/K0RQCC',
 'doi:10.7910/DVN/6M8RWP',
 'doi:10.7910/DVN/GEQXW4',
 'doi:10.7910/DVN/MQR1UM',
 'doi:10.7910/DVN/3P6VR7',
 'doi:10.7910/DVN/WTSWKL',
 'doi:10.7910/DVN/XKXUML',
 'doi:10.7910/DVN/URD3YB',
 'doi:10.7910/DVN/INJPMD',
 'doi:10.7910/DVN/9KC3ZL',
 'doi:10.7910/DVN/YG1QBV',
 'doi:10.7910/DVN/QUTL9J',
 'doi:10.7910/DVN/VZ1JNF',
 'doi:10.7910/DVN/VCMGFL',
 'doi:10.7910/DVN/7QCG22',
 'doi:10.7910/DVN/3TEFDD',
 'doi:10.7910/DVN/JNJFRH',
 'doi:10.7910/DVN/CVZMU6',
 'doi:10.7910/DVN/LGWPOQ',
 'doi:10.7910/DVN/BQIXPJ',
 'doi:10.7910/DVN/DDLGDS',
 'doi:10.7910/DVN/BRGQWI',
 'doi:10.7910/DVN/WLXTQA',
 'doi:10.7910/DVN/29ADOI',
 'doi:10.7910/DVN/C5ASD3',
 'doi:10.7910/DVN/I3HFKE',
 'doi:10.7910/DVN/004HG6',
 'doi:10.7910/DVN/FCCBFH',
 'doi:10.7910/DVN/X2QLXX',
 'doi:10.7910/DVN/AWRAT3',
 'doi:10.7910/DVN/GEWHGI',
 'doi:10.7910/DVN/PXJ3NN',
 'doi:10.7910/DVN/NUWKEZ',
 'doi:10.7910/DVN/1DGTIN',
 'doi:10.7910/DVN/N6CIE6',
 'doi:10.7910/DVN/58BAK6',
 'doi:10.7910/DVN/N64FVW',
 'doi:10.7910/DVN/PA6Q9B',
 'doi:10.7910/DVN/EA8ZFB',
 'doi:10.7910/DVN/XNYXML',
 'doi:10.7910/DVN/OMI2Z2',
 'doi:10.7910/DVN/OUIJWY',
 'doi:10.7910/DVN/32AYQR',
 'doi:10.7910/DVN/QBKSIO',
 'doi:10.7910/DVN/CV2LQH',
 'doi:10.7910/DVN/TCHNZS',
 'doi:10.7910/DVN/EHM3J8',
 'doi:10.7910/DVN/M3RYPM',
 'doi:10.7910/DVN/JXVJDW',
 'doi:10.7910/DVN/CUZND7',
 'doi:10.7910/DVN/2EFWM0',
 'doi:10.7910/DVN/MRG2VQ',
 'doi:10.7910/DVN/BUVDX1',
 'doi:10.7910/DVN/1NO8V3',
 'doi:10.7910/DVN/PUBXIM',
 'doi:10.7910/DVN/IFYFU4',
 'doi:10.7910/DVN/TUVZIP',
 'doi:10.7910/DVN/GX68V7',
 'doi:10.7910/DVN/NNIQDO',
 'doi:10.7910/DVN/NE6Y2U',
 'doi:10.7910/DVN/YNV1MC',
 'doi:10.7910/DVN/HTS79E',
 'doi:10.7910/DVN/SQKIOC',
 'doi:10.7910/DVN/OLXAZ0',
 'doi:10.7910/DVN/WB4AYS',
 'doi:10.7910/DVN/4KWEDF',
 'doi:10.7910/DVN/J2KIFO',
 'doi:10.7910/DVN/9JV2OI',
 'doi:10.7910/DVN/ZVVLTW',
 'doi:10.7910/DVN/6OVUND',
 'doi:10.7910/DVN/OWHTGP',
 'doi:10.7910/DVN/Y68EIH',
 'doi:10.7910/DVN/CFGT4M',
 'doi:10.7910/DVN/C2NBVB',
 'doi:10.7910/DVN/XFU2QU',
 'doi:10.7910/DVN/UEHCB9',
 'doi:10.7910/DVN/YJ6ZPZ',
 'doi:10.7910/DVN/EZMAYQ',
 'doi:10.7910/DVN/XH0VCX',
 'doi:10.7910/DVN/Q0BFZ4',
 'doi:10.7910/DVN/DA8V5Y',
 'doi:10.7910/DVN/ZMMXP7',
 'doi:10.7910/DVN/YL0ZZL',
 'doi:10.7910/DVN/TZVL57',
 'doi:10.7910/DVN/H7TWMJ',
 'doi:10.7910/DVN/SDE0JA',
 'doi:10.7910/DVN/QNKOFV',
 'doi:10.7910/DVN/DOHMY5',
 'doi:10.7910/DVN/SYV04M',
 'doi:10.7910/DVN/IKTHNG',
 'doi:10.7910/DVN/MRSS8A',
 'doi:10.7910/DVN/BI0CDY',
 'doi:10.7910/DVN/9FBO5M',
 'doi:10.7910/DVN/C23RO8',
 'doi:10.7910/DVN/LMH220',
 'doi:10.7910/DVN/XUPWX1',
 'doi:10.7910/DVN/ZJWUGO',
 'doi:10.7910/DVN/BDT5TQ',
 'doi:10.7910/DVN/7ORJ5X',
 'doi:10.7910/DVN/VWNPBA',
 'doi:10.7910/DVN/IDMPWY',
 'doi:10.7910/DVN/0E0E0I',
 'doi:10.7910/DVN/OWDDDR',
 'doi:10.7910/DVN/AMPR5U',
 'doi:10.7910/DVN/CACYOC',
 'doi:10.7910/DVN/FVNJ4D',
 'doi:10.7910/DVN/8VKM37',
 'doi:10.7910/DVN/ZJKKLQ',
 'doi:10.7910/DVN/CMSMQJ',
 'doi:10.7910/DVN/2MRCYV',
 'doi:10.7910/DVN/33VBFM',
 'doi:10.7910/DVN/6RNZDB',
 'doi:10.7910/DVN/VKWKHM',
 'doi:10.7910/DVN/EF9SIA',
 'doi:10.7910/DVN/GDXMQZ',
 'doi:10.7910/DVN/7KCGVZ',
 'doi:10.7910/DVN/4Y4MYF',
 'doi:10.7910/DVN/8QO2W2',
 'doi:10.7910/DVN/GKJDNZ',
 'doi:10.7910/DVN/KUK6HG',
 'doi:10.7910/DVN/JMWYZY',
 'doi:10.7910/DVN/RLJWG5',
 'doi:10.7910/DVN/O7ZRMR',
 'doi:10.7910/DVN/PMEW7W',
 'doi:10.7910/DVN/XSN03H',
 'doi:10.7910/DVN/2UOICE',
 'doi:10.7910/DVN/FKNI0W',
 'doi:10.7910/DVN/SZMYY2',
 'doi:10.7910/DVN/IJ4JRJ',
 'doi:10.7910/DVN/UDUGUN',
 'doi:10.7910/DVN/PVROPL',
 'doi:10.7910/DVN/NQYPB1',
 'doi:10.7910/DVN/ABWLXN',
 'doi:10.7910/DVN/0NFZCD',
 'doi:10.7910/DVN/YDPN1Z',
 'doi:10.7910/DVN/FRWJDK',
 'doi:10.7910/DVN/SCKHED',
 'doi:10.7910/DVN/EVE3YK',
 'doi:10.7910/DVN/1ZG5UE',
 'doi:10.7910/DVN/ZKOMOK',
 'doi:10.7910/DVN/WQL4BA',
 'doi:10.7910/DVN/VUX0LI',
 'doi:10.7910/DVN/UFBQIR',
 'doi:10.7910/DVN/K7I9UQ',
 'doi:10.7910/DVN/DM3F0T',
 'doi:10.7910/DVN/KGNV4S',
 'doi:10.7910/DVN/E9YLUX',
 'doi:10.7910/DVN/XUA15D',
 'doi:10.7910/DVN/RWY4VF',
 'doi:10.7910/DVN/EZJGT4',
 'doi:10.7910/DVN/PNHEPT',
 'doi:10.7910/DVN/ACJNWL',
 'doi:10.7910/DVN/OSXKJP',
 'doi:10.7910/DVN/WNY0UT',
 'doi:10.7910/DVN/QPUTJL',
 'doi:10.7910/DVN/AAQBFD',
 'doi:10.7910/DVN/2YYXZ8',
 'doi:10.7910/DVN/HWJL3V',
 'doi:10.7910/DVN/KTHHC7',
 'doi:10.7910/DVN/12INFV',
 'doi:10.7910/DVN/DVRDST',
 'doi:10.7910/DVN/KP1YZI',
 'doi:10.7910/DVN/ZFKO9G',
 'doi:10.7910/DVN/RNCRCR',
 'doi:10.7910/DVN/EOTIMX',
 'doi:10.7910/DVN/UCWZD6',
 'doi:10.7910/DVN/WOEN3X',
 'doi:10.7910/DVN/NM0LUS',
 'doi:10.7910/DVN/5TBXV2',
 'doi:10.7910/DVN/ZK8GMJ',
 'doi:10.7910/DVN/JBVCI8',
 'doi:10.7910/DVN/0OADUR',
 'doi:10.7910/DVN/CM3UCW',
 'doi:10.7910/DVN/PICCJM',
 'doi:10.7910/DVN/RXNYJA',
 'doi:10.7910/DVN/VNZZPX',
 'doi:10.7910/DVN/BNM5DS',
 'doi:10.7910/DVN/OCCM9H',
 'doi:10.7910/DVN/MGIN0P',
 'doi:10.7910/DVN/Z0LDER',
 'doi:10.7910/DVN/MZ3A2K',
 'doi:10.7910/DVN/YLTIFE',
 'doi:10.7910/DVN/BMEAWA',
 'doi:10.7910/DVN/IWUGIJ',
 'doi:10.7910/DVN/KU5EMF',
 'doi:10.7910/DVN/WV0SGJ',
 'doi:10.7910/DVN/OT2BXD',
 'doi:10.7910/DVN/ZGL0QX',
 'doi:10.7910/DVN/H75SPL',
 'doi:10.7910/DVN/KC9GL7',
 'doi:10.7910/DVN/ZCFNNC',
 'doi:10.7910/DVN/SBUDU8',
 'doi:10.7910/DVN/6VYTPF',
 'doi:10.7910/DVN/0QEAOI',
 'doi:10.7910/DVN/UMTG38',
 'doi:10.7910/DVN/M6V9FG',
 'doi:10.7910/DVN/P1J2QN',
 'doi:10.7910/DVN/XABCO6',
 'doi:10.7910/DVN/BYM2VN',
 'doi:10.7910/DVN/OJJGDB',
 'doi:10.7910/DVN/YUXQES',
 'doi:10.7910/DVN/HDI3LP',
 'doi:10.7910/DVN/YNRUQC',
 'doi:10.7910/DVN/KJGB4R',
 'doi:10.7910/DVN/1RQXGR',
 'doi:10.7910/DVN/X7B53O',
 'doi:10.7910/DVN/D8BYWD',
 'doi:10.7910/DVN/3IJH2O',
 'doi:10.7910/DVN/NIUXOD',
 'doi:10.7910/DVN/BTWZPX',
 'doi:10.7910/DVN/EFE57P',
 'doi:10.7910/DVN/YPQLKY',
 'doi:10.7910/DVN/U7XCX0',
 'doi:10.7910/DVN/ORBVQ5',
 'doi:10.7910/DVN/XJB9WC',
 'doi:10.7910/DVN/M4W4D3',
 'doi:10.7910/DVN/TOK4QS',
 'doi:10.7910/DVN/QTVS0R',
 'doi:10.7910/DVN/JCU2MD',
 'doi:10.7910/DVN/NLQDYU',
 'doi:10.7910/DVN/VC0O1N',
 'doi:10.7910/DVN/TXHWCW',
 'doi:10.7910/DVN/LDGYV5',
 'doi:10.7910/DVN/VEYNVE',
 'doi:10.7910/DVN/RA9IDS',
 'doi:10.7910/DVN/GXNDYB',
 'doi:10.7910/DVN/QW3JSD',
 'doi:10.7910/DVN/TZJMLE',
 'doi:10.7910/DVN/QWKT16',
 'doi:10.7910/DVN/FPR1GK',
 'doi:10.7910/DVN/S7COFT',
 'doi:10.7910/DVN/RCZI9H',
 'doi:10.7910/DVN/LBUIPQ',
 'doi:10.7910/DVN/FG4Z06',
 'doi:10.7910/DVN/XSYXMI',
 'doi:10.7910/DVN/HBU1WL',
 'doi:10.7910/DVN/WX5885',
 'doi:10.7910/DVN/ILQZPR',
 'doi:10.7910/DVN/NPAEB4',
 'doi:10.7910/DVN/GWZPND',
 'doi:10.7910/DVN/KFLCYN',
 'doi:10.7910/DVN/0MUV9I',
 'doi:10.7910/DVN/DGWCP6',
 'doi:10.7910/DVN/R82E9X',
 'doi:10.7910/DVN/6PBZVQ',
 'doi:10.7910/DVN/5NZ3LJ',
 'doi:10.7910/DVN/I9P8AE',
 'doi:10.7910/DVN/VLEVMY',
 'doi:10.7910/DVN/BBDK58',
 'doi:10.7910/DVN/9CADYW',
 'doi:10.7910/DVN/YSSQKX',
 'doi:10.7910/DVN/2LUDMK',
 'doi:10.7910/DVN/TUGXYR',
 'doi:10.7910/DVN/3KTXBC',
 'doi:10.7910/DVN/3GHUE1',
 'doi:10.7910/DVN/WJAUZB',
 'doi:10.7910/DVN/QDN4NO',
 'doi:10.7910/DVN/WHAJFW',
 'doi:10.7910/DVN/DJ4NFC',
 'doi:10.7910/DVN/JMS8DJ',
 'doi:10.7910/DVN/ZNVDB8',
 'doi:10.7910/DVN/5AXZP0',
 'doi:10.7910/DVN/7CBCID',
 'doi:10.7910/DVN/RW4KTP',
 'doi:10.7910/DVN/DUSRGK',
 'doi:10.7910/DVN/PMP4DG',
 'doi:10.7910/DVN/HV7VZK',
 'doi:10.7910/DVN/TIGSWT',
 'doi:10.7910/DVN/94HIVR',
 'doi:10.7910/DVN/FWVZ8X',
 'doi:10.7910/DVN/9E6PJR',
 'doi:10.7910/DVN/RT8ZSW',
 'doi:10.7910/DVN/SFBLRF',
 'doi:10.7910/DVN/WWJMHP',
 'doi:10.7910/DVN/4QWK0P',
 'doi:10.7910/DVN/TFWNOH',
 'doi:10.7910/DVN/L8X8NV',
 'doi:10.7910/DVN/JIFOIY',
 'doi:10.7910/DVN/JF3QQJ',
 'doi:10.7910/DVN/G3RUT6',
 'doi:10.7910/DVN/BCAOAS',
 'doi:10.7910/DVN/QK3M3D',
 'doi:10.7910/DVN/MTGYNW',
 'doi:10.7910/DVN/I31L2W',
 'doi:10.7910/DVN/HOIDS4',
 'doi:10.7910/DVN/I5A7G7',
 'doi:10.7910/DVN/KAHVMY',
 'doi:10.7910/DVN/7GJUEY',
 'doi:10.7910/DVN/RNKM1Y',
 'doi:10.7910/DVN/FJNGNY',
 'doi:10.7910/DVN/1CYP5S',
 'doi:10.7910/DVN/KK6W8S',
 'doi:10.7910/DVN/RJCZI7',
 'doi:10.7910/DVN/3EDTBH',
 'doi:10.7910/DVN/CLVYAM',
 'doi:10.7910/DVN/2Z9OPZ',
 'doi:10.7910/DVN/ANXH8U',
 'doi:10.7910/DVN/JCVAXP',
 'doi:10.7910/DVN/LWKUWK',
 'doi:10.7910/DVN/GKEXLR',
 'doi:10.7910/DVN/RU9TVT',
 'doi:10.7910/DVN/GGRO8T',
 'doi:10.7910/DVN/ENUNHE',
 'doi:10.7910/DVN/G878VK',
 'doi:10.7910/DVN/3ZTKRC',
 'doi:10.7910/DVN/WCUHFG',
 'doi:10.7910/DVN/Y4AEVE',
 'doi:10.7910/DVN/WGY97W',
 'doi:10.7910/DVN/LIUST7',
 'doi:10.7910/DVN/ELJOCA',
 'doi:10.7910/DVN/PD5KST',
 'doi:10.7910/DVN/XTRCOD',
 'doi:10.7910/DVN/ZZWWXB',
 'doi:10.7910/DVN/K6WADZ',
 'doi:10.7910/DVN/ZYV8DI',
 'doi:10.7910/DVN/BOFDGV',
 'doi:10.7910/DVN/TOY1SA',
 'doi:10.7910/DVN/PZRRUW',
 'doi:10.7910/DVN/0IUR8Z',
 'doi:10.7910/DVN/LSRRTE',
 'doi:10.7910/DVN/QCNRF7',
 'doi:10.7910/DVN/TGVXPA',

In [5]:
title = []

for d in dois:
    get_dataset_metadata_url = "%s/api/datasets/:persistentId/?persistentId=%s" % (base_url, d)
    r = requests.get(get_dataset_metadata_url, headers=headers)
    if r.json()['status'] == "OK":
        title.append(r.json()['data']['latestVersion']['metadataBlocks']['citation']['fields'][0]['value'])
        continue

dois_zip = list(zip(dois, title))
doi_df = pd.DataFrame(dois_zip, columns = ['doi', 'title'])

In [6]:
doi_df

                         doi          title
0     doi:10.7910/DVN/RQUTGG  A12_20683.JPG
1     doi:10.7910/DVN/U4B96B  A12_20684.JPG
2     doi:10.7910/DVN/SUJKSQ  A12_20685.JPG
3     doi:10.7910/DVN/0KRANR  A12_20686.JPG
4     doi:10.7910/DVN/SVT1ND  A12_20687.JPG
...                      ...            ...
2769  doi:10.7910/DVN/UFQPIF  A12_23892.JPG
2770  doi:10.7910/DVN/M9LJT8  A12_23893.JPG
2771  doi:10.7910/DVN/MSPYZ5  A12_23894.JPG
2772  doi:10.7910/DVN/NCS5JD  A12_23895.JPG
2773  doi:10.7910/DVN/EXFTAX  A12_23896.JPG

[2774 rows x 2 columns]

In [14]:
doi_df.to_csv('2012/dois_df.csv')

In [16]:
all_2012 = pd.read_csv("2012/2012_metadata.csv")
uploaded_dois = pd.read_csv("2012/dois_df.csv")

In [18]:
remaining_2012 = all_2012.merge(uploaded_dois, on=['filename'])
result = all_2012[~all_2012.filename.isin(remaining_2012.filename)]
result

                                             ochre_link       filename
819   http://pi.lib.uchicago.edu/1001/org/ochre/e9e8...   A12_21502JPG
848   http://pi.lib.uchicago.edu/1001/org/ochre/69ca...  A12_21531.jpg
947   http://pi.lib.uchicago.edu/1001/org/ochre/8dc7...  A12_21630.jpg
1288  http://pi.lib.uchicago.edu/1001/org/ochre/c164...  A12_21971.jpg
1785  http://pi.lib.uchicago.edu/1001/org/ochre/6c8f...  A12_22468.jpg
...                                                 ...            ...
3218  http://pi.lib.uchicago.edu/1001/org/ochre/b8ac...  A12_23903.jpg
3219  http://pi.lib.uchicago.edu/1001/org/ochre/8833...  A12_23904.jpg
3220  http://pi.lib.uchicago.edu/1001/org/ochre/0760...  A12_23905.jpg
3221  http://pi.lib.uchicago.edu/1001/org/ochre/dcd1...  A12_23906.jpg
3222  http://pi.lib.uchicago.edu/1001/org/ochre/3318...  A12_23907.jpg

[445 rows x 2 columns]

In [20]:
result['dv.dsDescription'] = '[{"dsDescriptionValue": "Link to OCHRE database: <a href = \'' + result['ochre_link']+ '\'>' + result['ochre_link'] + '\", \"dsDescriptionDate\": \"2022-03-01\"}]'
result.to_csv("missing_data/2012_missing_files.csv") #use this to manually create template files for datasets and datafiles

/opt/anaconda3/envs/dataverse/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.